# Generated by Django 4.0.2 on 2022-04-24 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users_pending_orders',
            field=models.ManyToManyField(blank=True, related_name='user_pending_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
